[tool.pytest.ini_options]
pythonpath = [
    ".",
    "airflow/dags"
]
testpaths = [
    "tests"
]
python_files = ["test_*.py", "*_test.py"]

[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta" 