"""Add venue_longitude to EventModel

Revision ID: 7b03196a3c2c
Revises: 30e957cc4ab7
Create Date: 2025-01-29 22:46:30.171079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b03196a3c2c'
down_revision: Union[str, None] = '30e957cc4ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('venue_longitude', sa.Float(), nullable=True))
    op.alter_column('events', 'venue_latitude', existing_type=sa.Float(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'venue_latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('events', 'venue_longitude')
    # ### end Alembic commands ###
