gcp:
  project_id: "prysm-prod"

database:
  url: ""  # Set via environment variable PRYSM_DATABASE__URL
  pool_size: 50
  max_overflow: 20

redis:
  host: ""  # Set via environment variable PRYSM_REDIS__HOST

auth:
  jwt_secret_key: ""  # Set via environment variable PRYSM_AUTH__JWT_SECRET_KEY

api:
  cors_origins:
    - "https://app.prysm.com"
  rate_limit: 1000
  rate_limit_period: 60

debug: false
log_level: "INFO" 